name: 'Download release-actions'
description: 'Downloads release-actions'
inputs:
  token:
    description: 'Personal access token that can access the red-gate/release-actions repository'
    required: true
  ref:
    description: 'The branch, tag or SHA to checkout. Defaults to specific commit for this version of the Release Actions.'
    default: 'v3.2.1'
    required: false
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        repository: red-gate/release-actions
        ref: ${{ inputs.ref }}
        path: release-actions
        token: ${{ inputs.token }}
